version: '3.3'
services:
    conteneur3:
      image: erwankerbrat/cours_cloud21
      ports:
        - "1021:5000"
      environment:
        url: "http://conteneur4:5000"
    conteneur4:
      image: erwankerbrat/cours_cloud22
      ports:
        - "1022:5000"
